[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.9"
futures = "0.3.30"
lazy_static = "1.5.0"
tokio = { version = "1.38.1", features = ["full"] }
tokio-util = {version = "0.7.11", features = ["full"]}
