[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.9"
futures = "0.3.30"
lazy_static = "1.5.0"
tokio = { version = "1.38.1", features = ["full"] }
tokio-util = {version = "0.7.11", features = ["full"]}
crossterm = "0.28.1"
dialoguer = "0.11.0"
rfd = "0.15.2"
notify-rust = "4.11.5"
rpassword = "7.3.1"
cpal = "0.15.3"
hound = "3.5.1"
rodio = "0.20.1"
